### ISSUE TITLE
Unhandled exception and SIGSEGV crash when DNS lookup fails.

### ISSUE THREAD

**Issue by GrahamDumpleton** [Kuadrant/authorino#182]
**Describe the bug**

A failed DNS lookup for:

```
  identity:
  - name: xxx
    oidc:
        endpoint: https://svc.ns.svc.cluster.local
```

generates an unhandled Golang exception and segmentation violation rather than being more nicely handled.

```
│ 2021-11-09T07:56:18.705Z    ERROR    authorino.identity.oidc    failed to discovery openid connect configuration │
│     {"endpoint": "https://svc.ns.svc.cluster.local", "error": "Get \"https:// │
│ svc.ns.svc.cluster.local/.well-known/openid-configuration\": dial tcp: lookup │
│  svc.ns.svc.cluster.local on 10.96.0.10:53: no such host"}                    │
│ github.com/kuadrant/authorino/pkg/config/identity.(*OIDC).getProvider                                            │
│     /workspace/pkg/config/identity/oidc.go:52                                                                    │
│ github.com/kuadrant/authorino/pkg/config/identity.(*OIDC).verifyToken                                            │
│     /workspace/pkg/config/identity/oidc.go:83                                                                    │
│ github.com/kuadrant/authorino/pkg/config/identity.(*OIDC).decodeAndVerifyToken                                   │
│     /workspace/pkg/config/identity/oidc.go:67                                                                    │
│ github.com/kuadrant/authorino/pkg/config/identity.(*OIDC).Call                                                   │
│     /workspace/pkg/config/identity/oidc.go:41                                                                    │
│ github.com/kuadrant/authorino/pkg/config.(*IdentityConfig).Call                                                  │
│     /workspace/pkg/config/identity.go:60                                                                         │
│ github.com/kuadrant/authorino/pkg/service.(*AuthPipeline).evaluateAuthConfig                                     │
│     /workspace/pkg/service/auth_pipeline.go:87                                                                   │
│ github.com/kuadrant/authorino/pkg/service.(*AuthPipeline).evaluateOneAuthConfig.func1                            │
│     /workspace/pkg/service/auth_pipeline.go:124                                                                  │
│ github.com/kuadrant/authorino/pkg/service.(*AuthPipeline).evaluateAuthConfigs.func1                              │
│     /workspace/pkg/service/auth_pipeline.go:115                                                                  │
│ panic: runtime error: invalid memory address or nil pointer dereference                                          │
│ [signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x1816bb6]                                         │
│ goroutine 552 [running]:                                                                                         │
│ github.com/coreos/go-oidc.(*Provider).Verifier(...)                                                              │
│     /go/pkg/mod/github.com/coreos/go-oidc@v2.2.1+incompatible/verify.go:110                                      │
│ github.com/kuadrant/authorino/pkg/config/identity.(*OIDC).verifyToken(0xc00024db90, 0xc0001d8007, 0x36d, 0x1f5ec │
│ e0, 0xc000720b00, 0x40e078, 0x10, 0x1a4bca0)                                                                     │
│     /workspace/pkg/config/identity/oidc.go:83 +0x76                                                              │
│ github.com/kuadrant/authorino/pkg/config/identity.(*OIDC).decodeAndVerifyToken(0xc00024db90, 0xc0001d8007, 0x36d │
│ , 0x1f5ece0, 0xc000720b00, 0xc000a34990, 0x1, 0xc0004d05a0, 0x8ef029)                                            │
│     /workspace/pkg/config/identity/oidc.go:67 +0xbf                                                              │
│ github.com/kuadrant/authorino/pkg/config/identity.(*OIDC).Call(0xc00024db90, 0x1f70730, 0xc000720ac0, 0x1f5ece0, │
│  0xc000720b00, 0x161203e, 0x0, 0xc0004d05a0, 0xc0001b6300)                                                       │
│     /workspace/pkg/config/identity/oidc.go:41 +0x110                                                             │
│ github.com/kuadrant/authorino/pkg/config.(*IdentityConfig).Call(0xc00053c420, 0x1f70730, 0xc000720ac0, 0x1f5ece0 │
│ , 0xc000720b00, 0x0, 0x0, 0x0, 0xc000745758)                                                                     │
│     /workspace/pkg/config/identity.go:60 +0x71                                                                   │
│ github.com/kuadrant/authorino/pkg/service.(*AuthPipeline).evaluateAuthConfig(0xc000720ac0, 0x1f22460, 0xc00053c4 │
│ 20, 0x1f5ece0, 0xc000720b00, 0xc000140750, 0xc000a34980, 0x0)                                                    │
│     /workspace/pkg/service/auth_pipeline.go:87 +0x1cc                                                            │
│ github.com/kuadrant/authorino/pkg/service.(*AuthPipeline).evaluateOneAuthConfig.func1(0x1f22460, 0xc00053c420, 0 │
│ x1f5ece0, 0xc000720b00, 0xc000140750, 0xc000a34980)                                                              │
│     /workspace/pkg/service/auth_pipeline.go:124 +0x6f                                                            │
│ github.com/kuadrant/authorino/pkg/service.(*AuthPipeline).evaluateAuthConfigs.func1(0xc000917780, 0xc000a34970,  │
│ 0x1f22460, 0xc00053c420, 0x1f5ece0, 0xc000720b00, 0xc000140750, 0xc000a34980)                                    │
│     /workspace/pkg/service/auth_pipeline.go:115 +0x97                                                            │
│ created by github.com/kuadrant/authorino/pkg/service.(*AuthPipeline).evaluateAuthConfigs                         │
│     /workspace/pkg/service/auth_pipeline.go:113 +0x145                                                           │
```

**Help us Reproduce it**

Set up `oidc` endpoint for JWT token verification where the hostname is incorrect.

**Expected behavior**

Nicer error message rather than Golang stack trace.

**Environment (please complete the following information):**

```
quay.io/3scale/authorino:v0.4.0
```

**Comment by GrahamDumpleton** [comment]
Semi related, nicer error handling might be had for timeout as well. No crash this time at least.

```
│ xdsauthz-developer-portal-1-65c5ff65c4-rt6cf 2021-11-09T08:06:18.858Z    ERROR    authorino.identity.oidc    fai │
│ led to discovery openid connect configuration    {"endpoint": "https://svc.ns.svc.cluster.local", │
│ "error": "Get \"https://svc.ns.svc.cluster.local/. │
│ well-known/openid-configuration\": dial tcp 10.96.149.184:443: i/o timeout"}                                     │
│ xdsauthz-developer-portal-1-65c5ff65c4-rt6cf github.com/kuadrant/authorino/pkg/config/identity.(*OIDC).getProvid │
│ er                                                                                                               │
│ xdsauthz-developer-portal-1-65c5ff65c4-rt6cf     /workspace/pkg/config/identity/oidc.go:52                       │
│ xdsauthz-developer-portal-1-65c5ff65c4-rt6cf github.com/kuadrant/authorino/pkg/config/identity.NewOIDC           │
│ xdsauthz-developer-portal-1-65c5ff65c4-rt6cf     /workspace/pkg/config/identity/oidc.go:27                       │
│ xdsauthz-developer-portal-1-65c5ff65c4-rt6cf github.com/kuadrant/authorino/controllers.(*AuthConfigReconciler).t │
│ ranslateAuthConfig                                                                                               │
│ xdsauthz-developer-portal-1-65c5ff65c4-rt6cf     /workspace/controllers/auth_config_controller.go:144            │
│ xdsauthz-developer-portal-1-65c5ff65c4-rt6cf github.com/kuadrant/authorino/controllers.(*AuthConfigReconciler).R │
│ econcile                                                                                                         │
│ xdsauthz-developer-portal-1-65c5ff65c4-rt6cf     /workspace/controllers/auth_config_controller.go:76             │
│ xdsauthz-developer-portal-1-65c5ff65c4-rt6cf sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller │
│ ).reconcileHandler                                                                                               │
│ xdsauthz-developer-portal-1-65c5ff65c4-rt6cf     /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/ │
│ controller/controller.go:298                                                                                     │
│ xdsauthz-developer-portal-1-65c5ff65c4-rt6cf sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller │
│ ).processNextWorkItem                                                                                            │
│ xdsauthz-developer-portal-1-65c5ff65c4-rt6cf     /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/ │
│ controller/controller.go:253                                                                                     │
│ xdsauthz-developer-portal-1-65c5ff65c4-rt6cf sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller │
│ ).Start.func2.2                                                                                                  │
│ xdsauthz-developer-portal-1-65c5ff65c4-rt6cf     /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/ │
│ controller/controller.go:214 
```

**Comment by GrahamDumpleton** [comment]
And another variation which causes a crash. This time where the certificate validation fails for hostname of certificate not matching.

```
│ 2021-11-09T08:13:51.987Z    ERROR    authorino.identity.oidc    failed to discovery openid connect configuration │
│     {"endpoint": "https://svc.ns.svc.cluster.local:5556", "error": "Get \" │
│ https://svc.ns.svc.cluster.local:5556/.well-known/openid-configuration\":  │
│ x509: certificate is valid for *.example.com, not svc.ns.svc.cluster.local"}                                                                                                          │
│ github.com/kuadrant/authorino/pkg/config/identity.(*OIDC).getProvider                                            │
│     /workspace/pkg/config/identity/oidc.go:52                                                                    │
│ github.com/kuadrant/authorino/pkg/config/identity.(*OIDC).verifyToken                                            │
│     /workspace/pkg/config/identity/oidc.go:83                                                                    │
│ github.com/kuadrant/authorino/pkg/config/identity.(*OIDC).decodeAndVerifyToken                                   │
│     /workspace/pkg/config/identity/oidc.go:67                                                                    │
│ github.com/kuadrant/authorino/pkg/config/identity.(*OIDC).Call                                                   │
│     /workspace/pkg/config/identity/oidc.go:41                                                                    │
│ github.com/kuadrant/authorino/pkg/config.(*IdentityConfig).Call                                                  │
│     /workspace/pkg/config/identity.go:60                                                                         │
│ github.com/kuadrant/authorino/pkg/service.(*AuthPipeline).evaluateAuthConfig                                     │
│     /workspace/pkg/service/auth_pipeline.go:87                                                                   │
│ github.com/kuadrant/authorino/pkg/service.(*AuthPipeline).evaluateOneAuthConfig.func1                            │
│     /workspace/pkg/service/auth_pipeline.go:124                                                                  │
│ github.com/kuadrant/authorino/pkg/service.(*AuthPipeline).evaluateAuthConfigs.func1                              │
│     /workspace/pkg/service/auth_pipeline.go:115                                                                  │
│ panic: runtime error: invalid memory address or nil pointer dereference                                          │
│ [signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x1816bb6]                                         │
│ goroutine 464 [running]:                                                                                         │
│ github.com/coreos/go-oidc.(*Provider).Verifier(...)                                                              │
│     /go/pkg/mod/github.com/coreos/go-oidc@v2.2.1+incompatible/verify.go:110                                      │
│ github.com/kuadrant/authorino/pkg/config/identity.(*OIDC).verifyToken(0xc000a93110, 0xc000c99887, 0x36d, 0x1f5ec │
│ e0, 0xc000822d00, 0x40e078, 0x10, 0x1a4bca0)                                                                     │
│     /workspace/pkg/config/identity/oidc.go:83 +0x76                                                              │
│ github.com/kuadrant/authorino/pkg/config/identity.(*OIDC).decodeAndVerifyToken(0xc000a93110, 0xc000c99887, 0x36d │
│ , 0x1f5ece0, 0xc000822d00, 0xc00072ee40, 0x1, 0xc0009f1d40, 0xc0008bede0)                                        │
│     /workspace/pkg/config/identity/oidc.go:67 +0xbf                                                              │
│ github.com/kuadrant/authorino/pkg/config/identity.(*OIDC).Call(0xc000a93110, 0x1f70730, 0xc000822cc0, 0x1f5ece0, │
│  0xc000822d00, 0x161203e, 0x0, 0xc0009f1d40, 0xc0008bef00)                                                       │
│     /workspace/pkg/config/identity/oidc.go:41 +0x110                                                             │
│ github.com/kuadrant/authorino/pkg/config.(*IdentityConfig).Call(0xc00001e600, 0x1f70730, 0xc000822cc0, 0x1f5ece0 │
│ , 0xc000822d00, 0x0, 0x0, 0x2, 0x0)                                                                              │
│     /workspace/pkg/config/identity.go:60 +0x71                                                                   │
│ github.com/kuadrant/authorino/pkg/service.(*AuthPipeline).evaluateAuthConfig(0xc000822cc0, 0x1f22460, 0xc00001e6 │
│ 00, 0x1f5ece0, 0xc000822d00, 0xc0001de0b0, 0xc00072ee30, 0x0)                                                    │
│     /workspace/pkg/service/auth_pipeline.go:87 +0x1cc                                                            │
│ github.com/kuadrant/authorino/pkg/service.(*AuthPipeline).evaluateOneAuthConfig.func1(0x1f22460, 0xc00001e600, 0 │
│ x1f5ece0, 0xc000822d00, 0xc0001de0b0, 0xc00072ee30)                                                              │
│     /workspace/pkg/service/auth_pipeline.go:124 +0x6f                                                            │
│ github.com/kuadrant/authorino/pkg/service.(*AuthPipeline).evaluateAuthConfigs.func1(0xc0004b5300, 0xc00072ee20,  │
│ 0x1f22460, 0xc00001e600, 0x1f5ece0, 0xc000822d00, 0xc0001de0b0, 0xc00072ee30)                                    │
│     /workspace/pkg/service/auth_pipeline.go:115 +0x97                                                            │
│ created by github.com/kuadrant/authorino/pkg/service.(*AuthPipeline).evaluateAuthConfigs                         │
│     /workspace/pkg/service/auth_pipeline.go:113 +0x145                                                           │
```

**Comment by guicassolato** [comment]
Thanks for reporting this, @GrahamDumpleton!

I see you're using v0.4.0. v0.5.0 has some improved logging, so I'll make sure to test and compare against this newer version as well.

Either way, the `SIGSEGV` is not cool and should be handled better. I'm labeling this as a bug.

An additional thing to notice is that `identity.(*OIDC).getProvider` is called in [reconciliation-time](https://github.com/Kuadrant/authorino/blob/ecc93ab701dc56c5afdecf8ee9b0298e279ece0e/pkg/config/identity/oidc.go#L25) and, when that one time fails (without crashing), and therefore the OIDC config cache is missing, again in [request-time](https://github.com/Kuadrant/authorino/blob/ecc93ab701dc56c5afdecf8ee9b0298e279ece0e/pkg/config/identity/oidc.go#L81). Soon, once #181 gets merged, `getProvider` will also get invoked by a timer, to refresh the cache on a schedule.

I guess a non-exhaustive list of scenarios to cover then is:

<table>
  <thead>
    <tr>
      <th>When</th>
      <th>What</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td rowspan="3"><code>AuthConfig</code> Reconciliation</td>
      <td>DNS lookup failed</td>
    </tr>
    <tr>
      <td>Timeout</td>
    </tr>
    <tr>
      <td>Invalid x509 certificate</td>
    </tr>
    <tr>
      <td rowspan="3">Request-time(*)</td>
      <td>DNS lookup failed</td>
    </tr>
    <tr>
      <td>Timeout</td>
    </tr>
    <tr>
      <td>Invalid x509 certificate</td>
    </tr>
    <tr>
      <td rowspan="3">Cache refresh(**)</td>
      <td>DNS lookup failed</td>
    </tr>
    <tr>
      <td>Timeout</td>
    </tr>
    <tr>
      <td>Invalid x509 certificate</td>
    </tr>
  </tbody>
</table>

(*) After failing first in reconciliation-time without `SIGSEGV`.
(**) For #181.
